import { ReportCategory } from "../types";

export const INITIAL_REPORT_CATEGORIES: ReportCategory[] = [
  {
    id: "cat_unlawful_detention",
    code: "unlawful_detention",
    name: "Unlawful Detention",
    description:
      "Being held in custody, arrested, or detained without lawful authority, due process, or judicial review.",
    hint: "Being held without lawful reason or process",
    icon: "lock",
    isActive: true,
    isSystemDefault: true,
    displayOrder: 1,
    activeCaseCount: 14,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "cat_discrimination",
    code: "discrimination",
    name: "Discrimination",
    description:
      "Unfair treatment or denial of rights based on ethnicity, religion, gender, sexual orientation, disability, or social status.",
    hint: "Unfair treatment based on who you are",
    icon: "scale",
    isActive: true,
    isSystemDefault: true,
    displayOrder: 2,
    activeCaseCount: 9,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "cat_violence_abuse",
    code: "violence_or_abuse",
    name: "Violence or Abuse",
    description:
      "Physical assault, excessive use of force by authorities, torture, cruel, inhuman, or degrading treatment.",
    hint: "Physical harm, threats or ill-treatment",
    icon: "shield-alert",
    isActive: true,
    isSystemDefault: true,
    displayOrder: 3,
    activeCaseCount: 22,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "cat_harassment",
    code: "harassment",
    name: "Harassment & Intimidation",
    description:
      "Repeated stalking, digital harassment, surveillance, extortion, or threats aimed at silencing individuals.",
    hint: "Repeated unwanted behaviour or intimidation",
    icon: "alert-triangle",
    isActive: true,
    isSystemDefault: true,
    displayOrder: 4,
    activeCaseCount: 11,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "cat_freedom_expression",
    code: "freedom_of_expression",
    name: "Freedom of Expression Violation",
    description:
      "Suppression of free speech, peaceful assembly, press freedom, censorship, or unlawful confiscation of reporting equipment.",
    hint: "Being stopped from speaking or assembling",
    icon: "message-square",
    isActive: true,
    isSystemDefault: true,
    displayOrder: 5,
    activeCaseCount: 6,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "cat_workplace_rights",
    code: "workplace_rights",
    name: "Workplace Rights Violation",
    description:
      "Forced labor, hazardous working conditions, withholding of wages, union busting, or child labor.",
    hint: "Unsafe, unpaid or unfair working conditions",
    icon: "document",
    isActive: true,
    isSystemDefault: true,
    displayOrder: 6,
    activeCaseCount: 8,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "cat_child_rights",
    code: "child_rights",
    name: "Child Rights Violation",
    description:
      "Harm, exploitation, neglect, denial of education, or abuse affecting minors and children.",
    hint: "Harm or denial of rights affecting a child",
    icon: "shield",
    isActive: true,
    isSystemDefault: true,
    displayOrder: 7,
    activeCaseCount: 4,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "cat_gender_based_violence",
    code: "gender_based_violence",
    name: "Gender-Based Violence",
    description:
      "Violence, assault, coercive control, or domestic abuse inflicted against individuals based on gender identity.",
    hint: "Harm or abuse directed against a person based on gender",
    icon: "alert-circle",
    isActive: true,
    isSystemDefault: true,
    displayOrder: 8,
    activeCaseCount: 16,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "cat_health_basic_services",
    code: "health_basic_services",
    name: "Right to Health & Basic Services",
    description:
      "Denial of emergency medical care, clean water, essential shelter, or discriminatory access to public relief.",
    hint: "Deprivation of essential healthcare, water, or shelter",
    icon: "activity",
    isActive: true,
    isSystemDefault: true,
    displayOrder: 9,
    activeCaseCount: 5,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "cat_other",
    code: "other",
    name: "Other Human Rights Violation",
    description:
      "Other incidents or rights violations not specifically listed in the predefined categories above.",
    hint: "Something not listed here",
    icon: "category",
    isActive: true,
    isSystemDefault: true,
    displayOrder: 10,
    activeCaseCount: 19,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];
